using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;    // need this for the "[Key]" attribute

namespace IT2030_Lab04_Mosinski_MusicStore.Models
{
    public class Cart
    {
        [Key]   // this tells Entity Framework that 'RecordID' is the primary key and not 'CartID'
        public int RecordId { get; set; }       // This will be auto-generated by EF
        public string CartID { get; set; }   // Not unique; Can be common for multiple cart items that belong to 1 user - that's how we know who's cart it is
        public int AlbumId { get; set; }
        public int Count { get; set; }
        public virtual Album AlbumSelected { get; set; }    // This is a navigation property; this is going to link the cart to the album. ALWAYS HAS TO BE VIRTUAL
        public DateTime DateCreated { get; set; }
    }
}